// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelW6Fq6y5vmy0d2UfflDPRmRzdy8cI14',
    appId: '1:1077568520492:web:10f382edb0ed3ebedd6c89',
    messagingSenderId: '1077568520492',
    projectId: 'outbye-e17d3',
    authDomain: 'outbye-e17d3.firebaseapp.com',
    storageBucket: 'outbye-e17d3.firebasestorage.app',
    measurementId: 'G-3R0GHVGK47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkUhnIkBOm5iL-UBWFiHAg8A7PWpCd_Hg',
    appId: '1:1077568520492:android:d5286f508caaedc4dd6c89',
    messagingSenderId: '1077568520492',
    projectId: 'outbye-e17d3',
    storageBucket: 'outbye-e17d3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelW6Fq6y5vmy0d2UfflDPRmRzdy8cI14',
    appId: '1:1077568520492:web:c76706c87b724f15dd6c89',
    messagingSenderId: '1077568520492',
    projectId: 'outbye-e17d3',
    authDomain: 'outbye-e17d3.firebaseapp.com',
    storageBucket: 'outbye-e17d3.firebasestorage.app',
    measurementId: 'G-K0169PK2MV',
  );
}
